name: build and push microservices

on:
  push:
    branches:
      - feature/level-service
env:
  REGISTRY: docker.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    strategy:
      matrix:
        image_name: ["level-service"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        working-directory: ${{matrix.image_name}}
        run: mvn -B package --file pom.xml

      - name: Dockerize & Push Docker ${{matrix.image_name}}
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          directory: ${{matrix.image_name}}
          image: ${{secrets.DOCKER_USERNAME}}/${{matrix.image_name}}
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
